run_onnx_menoh should depend on menoh_chainer_compiler_cc_inc
This fix the following compilation error.
```
Scanning dependencies of target run_onnx_menoh
[ 97%] Building CXX object menoh/CMakeFiles/run_onnx_menoh.dir/run_onnx.cpp.o
chainer-compiler/menoh/run_onnx.cpp:160:10: fatal error: 'menoh/args_json.inc' file not found
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
```